
on:
  workflow_dispatch:

jobs:
  send-banking-polls:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Banking Quiz Bot
        run: python banking_poll.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BANKING_CHAT_ID: ${{ secrets.BANKING_CHAT_ID }}
